version: '3'
services:
  sapl-server:
    image: ghcr.io/heutelbeck/sapl-server-lt:2.1.0-snapshot
    ports:
      - "8080:8080"
    volumes:
      - .\sapl_policies:/pdp/data

  flask-app:
    image: sapl-flask-demo:latest
    depends_on:
      - sapl-server
    ports:
      - "5000:5000"