# Generated by Django 4.1.2 on 2022-11-13 21:16

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('icd11_code', models.CharField(blank=True, default='', max_length=64)),
                ('diagnosis_text', models.TextField(max_length=4096)),
                ('attending_doctor', models.CharField(blank=True, default='', max_length=64)),
                ('room_number', models.IntegerField()),
                ('is_related_to_staff', models.BooleanField(default=False)),
            ],
            managers=[
                ('objects_patients', django.db.models.manager.Manager()),
            ],
        ),
    ]
